// // C:\webchaiyo\Waterapp\resources\js\pages\product\Pump.ts
// export const PumpData = [
//     // --- ข้อมูลจากรูปที่ 1 (ปั๊มเจ็ท) ---
//     {
//         id: 1,
//         productCode: '1-CJP-K160',
//         powerHP: 1.5,
//         powerKW: 1.1, // fake
//         phase: 1, // fake
//         inlet_size_inch: 1.5,
//         outlet_size_inch: 1.5,
//         flow_rate_lpm: [100, 280],
//         head_m: [22, 10],
//         max_head_m: 22, // fake
//         max_flow_rate_lpm: 280, // fake
//         suction_depth_m: 10, // fake
//         dimensions_cm: '19 x 35 x 25',
//         weight_kg: 19.48,
//         price: 6420,
//     },
//     {
//         id: 2,
//         productCode: '1-CJP-K407',
//         powerHP: 2,
//         powerKW: 1.5, // fake
//         phase: 1, // fake
//         inlet_size_inch: 2,
//         outlet_size_inch: 2,
//         flow_rate_lpm: [100, 450],
//         head_m: [22, 10],
//         max_head_m: 22, // fake
//         max_flow_rate_lpm: 450, // fake
//         suction_depth_m: 10, // fake
//         dimensions_cm: '19 x 35 x 25',
//         weight_kg: 19.5,
//         price: 7000,
//     },
//     {
//         id: 3,
//         productCode: '1-CJP-K1506',
//         powerHP: '2 (หน้าแปลน)', // 2 HP (Flanged)
//         powerKW: 1.5, // fake
//         phase: 1, // fake
//         inlet_size_inch: 2,
//         outlet_size_inch: 2,
//         flow_rate_lpm: [100, 500],
//         head_m: [40, 10],
//         max_head_m: 40, // fake
//         max_flow_rate_lpm: 500, // fake
//         suction_depth_m: 10, // fake
//         dimensions_cm: '20 x 39 x 25',
//         weight_kg: 25.6,
//         price: 7500,
//     },

//     // --- ข้อมูลจากรูปที่ 2 (ปั๊มหอยโข่ง CPM) ---
//     {
//         id: 4,
//         productCode: '1-CPM130',
//         powerHP: 0.5,
//         powerKW: 0.37,
//         phase: 1,
//         inlet_size_inch: 1,
//         outlet_size_inch: 1,
//         flow_rate_lpm: [100, 80], // fake
//         head_m: [18, 10], // fake
//         max_head_m: 18,
//         max_flow_rate_lpm: 80,
//         suction_depth_m: 9,
//         dimensions_cm: null,
//         weight_kg: null,
//         price: 1820,
//     },
//     {
//         id: 5,
//         productCode: '1-CPM158',
//         powerHP: 1.0,
//         powerKW: 0.75,
//         phase: 1,
//         inlet_size_inch: 1,
//         outlet_size_inch: 1,
//         flow_rate_lpm: [100, 97], // fake
//         head_m: [23, 10], // fake
//         max_head_m: 23,
//         max_flow_rate_lpm: 97,
//         suction_depth_m: 9,
//         dimensions_cm: null,
//         weight_kg: null,
//         price: 2675,
//     },
//     {
//         id: 6,
//         productCode: '1-CPM200',
//         powerHP: 2.0,
//         powerKW: 1.5,
//         phase: 1,
//         inlet_size_inch: 2,
//         outlet_size_inch: 2,
//         flow_rate_lpm: [100, 368], // fake
//         head_m: [20, 10], // fake
//         max_head_m: 20,
//         max_flow_rate_lpm: 368,
//         suction_depth_m: 9,
//         dimensions_cm: null,
//         weight_kg: null,
//         price: 3745,
//     },
//     {
//         id: 7,
//         productCode: '1-CPM300',
//         powerHP: 3.0,
//         powerKW: 2.2,
//         phase: 1,
//         inlet_size_inch: 2,
//         outlet_size_inch: 2,
//         flow_rate_lpm: [100, 435], // fake
//         head_m: [20, 10], // fake
//         max_head_m: 20,
//         max_flow_rate_lpm: 435,
//         suction_depth_m: 9,
//         dimensions_cm: null,
//         weight_kg: null,
//         price: 5510,
//     },

//     // --- ข้อมูลจากรูปที่ 3 (ปั๊มหอยโข่ง NFM) ---
//     {
//         id: 8,
//         productCode: '1-NFM130A',
//         powerHP: 3,
//         powerKW: 2.2,
//         phase: 1,
//         inlet_size_inch: 3,
//         outlet_size_inch: 3,
//         flow_rate_lpm: [100, 868], // fake
//         head_m: [14, 10], // fake
//         max_head_m: 14,
//         max_flow_rate_lpm: 868,
//         suction_depth_m: 9,
//         dimensions_cm: null,
//         weight_kg: null,
//         price: 5680,
//     },
//     // fake
//     {
//         id: 9,
//         productCode: '1-NFM158B',
//         powerHP: 1.5,
//         powerKW: 1.1,
//         phase: 1,
//         inlet_size_inch: 4,
//         outlet_size_inch: 4,
//         flow_rate_lpm: [100, 1000], // fake
//         head_m: [14, 10], // fake
//         max_head_m: 14,
//         max_flow_rate_lpm: 1000,
//         suction_depth_m: 9,
//         dimensions_cm: null,
//         weight_kg: null,
//         price: 9500,
//     },
//     {
//         id: 10,
//         productCode: '1-NFM200C',
//         powerHP: 2,
//         powerKW: 1.5,
//         phase: 1,
//         inlet_size_inch: 4,
//         outlet_size_inch: 4,
//         flow_rate_lpm: [100, 900], // fake
//         head_m: [14, 10], // fake
//         max_head_m: 14,
//         max_flow_rate_lpm: 900,
//         suction_depth_m: 9,
//         dimensions_cm: null,
//         weight_kg: null,
//         price: 8500,
//     }

// ];

export const PumpData = [
    // --- ข้อมูลเดิม (ปั๊มเจ็ท) ---
    {
        id: 1,
        productCode: '1-CJP-K160',
        powerHP: 1.5,
        powerKW: 1.1,
        phase: 1,
        inlet_size_inch: 1.5,
        outlet_size_inch: 1.5,
        flow_rate_lpm: [100, 280],
        head_m: [22, 10],
        max_head_m: 22,
        max_flow_rate_lpm: 280,
        suction_depth_m: 10,
        dimensions_cm: '19 x 35 x 25',
        weight_kg: 19.48,
        price: 6420,
    },
    {
        id: 2,
        productCode: '1-CJP-K407',
        powerHP: 2,
        powerKW: 1.5,
        phase: 1,
        inlet_size_inch: 2,
        outlet_size_inch: 2,
        flow_rate_lpm: [100, 450],
        head_m: [22, 10],
        max_head_m: 22,
        max_flow_rate_lpm: 450,
        suction_depth_m: 10,
        dimensions_cm: '19 x 35 x 25',
        weight_kg: 19.5,
        price: 7000,
    },
    {
        id: 3,
        productCode: '1-CJP-K1506',
        powerHP: '2 (หน้าแปลน)',
        powerKW: 1.5,
        phase: 1,
        inlet_size_inch: 2,
        outlet_size_inch: 2,
        flow_rate_lpm: [100, 500],
        head_m: [40, 10],
        max_head_m: 40,
        max_flow_rate_lpm: 500,
        suction_depth_m: 10,
        dimensions_cm: '20 x 39 x 25',
        weight_kg: 25.6,
        price: 7500,
    },

    // --- ปั๊มหอยโข่ง CPM (เดิม) ---
    {
        id: 4,
        productCode: '1-CPM130',
        powerHP: 0.5,
        powerKW: 0.37,
        phase: 1,
        inlet_size_inch: 1,
        outlet_size_inch: 1,
        flow_rate_lpm: [100, 80],
        head_m: [18, 10],
        max_head_m: 18,
        max_flow_rate_lpm: 80,
        suction_depth_m: 9,
        dimensions_cm: null,
        weight_kg: null,
        price: 1820,
    },
    {
        id: 5,
        productCode: '1-CPM158',
        powerHP: 1.0,
        powerKW: 0.75,
        phase: 1,
        inlet_size_inch: 1,
        outlet_size_inch: 1,
        flow_rate_lpm: [100, 97],
        head_m: [23, 10],
        max_head_m: 23,
        max_flow_rate_lpm: 97,
        suction_depth_m: 9,
        dimensions_cm: null,
        weight_kg: null,
        price: 2675,
    },
    {
        id: 6,
        productCode: '1-CPM200',
        powerHP: 2.0,
        powerKW: 1.5,
        phase: 1,
        inlet_size_inch: 2,
        outlet_size_inch: 2,
        flow_rate_lpm: [100, 368],
        head_m: [20, 10],
        max_head_m: 20,
        max_flow_rate_lpm: 368,
        suction_depth_m: 9,
        dimensions_cm: null,
        weight_kg: null,
        price: 3745,
    },
    {
        id: 7,
        productCode: '1-CPM300',
        powerHP: 3.0,
        powerKW: 2.2,
        phase: 1,
        inlet_size_inch: 2,
        outlet_size_inch: 2,
        flow_rate_lpm: [100, 435],
        head_m: [20, 10],
        max_head_m: 20,
        max_flow_rate_lpm: 435,
        suction_depth_m: 9,
        dimensions_cm: null,
        weight_kg: null,
        price: 5510,
    },

    // --- ปั๊มหอยโข่ง NFM (เดิม) ---
    {
        id: 8,
        productCode: '1-NFM130A',
        powerHP: 3,
        powerKW: 2.2,
        phase: 1,
        inlet_size_inch: 3,
        outlet_size_inch: 3,
        flow_rate_lpm: [100, 868],
        head_m: [14, 10],
        max_head_m: 14,
        max_flow_rate_lpm: 868,
        suction_depth_m: 9,
        dimensions_cm: null,
        weight_kg: null,
        price: 5680,
    },
    {
        id: 9,
        productCode: '1-NFM158B',
        powerHP: 1.5,
        powerKW: 1.1,
        phase: 1,
        inlet_size_inch: 4,
        outlet_size_inch: 4,
        flow_rate_lpm: [100, 1000],
        head_m: [14, 10],
        max_head_m: 14,
        max_flow_rate_lpm: 1000,
        suction_depth_m: 9,
        dimensions_cm: null,
        weight_kg: null,
        price: 9500,
    },
    {
        id: 10,
        productCode: '1-NFM200C',
        powerHP: 2,
        powerKW: 1.5,
        phase: 1,
        inlet_size_inch: 4,
        outlet_size_inch: 4,
        flow_rate_lpm: [100, 900],
        head_m: [14, 10],
        max_head_m: 14,
        max_flow_rate_lpm: 900,
        suction_depth_m: 9,
        dimensions_cm: null,
        weight_kg: null,
        price: 8500,
    },

    // === เพิ่มใหม่ - ปั๊มขนาดเล็ก (สำหรับสวนเล็ก) ===
    {
        id: 11,
        productCode: '1-CPM075',
        powerHP: 0.25,
        powerKW: 0.18,
        phase: 1,
        inlet_size_inch: 0.75,
        outlet_size_inch: 0.75,
        flow_rate_lpm: [10, 45],
        head_m: [15, 8],
        max_head_m: 15,
        max_flow_rate_lpm: 45,
        suction_depth_m: 8,
        dimensions_cm: '15 x 25 x 18',
        weight_kg: 8.5,
        price: 1250,
    },
    {
        id: 12,
        productCode: '1-CPM100',
        powerHP: 0.33,
        powerKW: 0.25,
        phase: 1,
        inlet_size_inch: 1,
        outlet_size_inch: 1,
        flow_rate_lpm: [20, 60],
        head_m: [16, 9],
        max_head_m: 16,
        max_flow_rate_lpm: 60,
        suction_depth_m: 8,
        dimensions_cm: '16 x 28 x 20',
        weight_kg: 10.2,
        price: 1450,
    },

    // === เพิ่มใหม่ - ปั๊มขนาดกลาง (3-5 HP) ===
    {
        id: 13,
        productCode: '1-CPM500',
        powerHP: 5.0,
        powerKW: 3.7,
        phase: 1,
        inlet_size_inch: 3,
        outlet_size_inch: 3,
        flow_rate_lpm: [200, 750],
        head_m: [28, 15],
        max_head_m: 28,
        max_flow_rate_lpm: 750,
        suction_depth_m: 9,
        dimensions_cm: '45 x 35 x 30',
        weight_kg: 45.8,
        price: 8950,
    },
    {
        id: 14,
        productCode: '1-CJP-K750',
        powerHP: 4.0,
        powerKW: 3.0,
        phase: 1,
        inlet_size_inch: 2.5,
        outlet_size_inch: 2.5,
        flow_rate_lpm: [150, 680],
        head_m: [35, 18],
        max_head_m: 35,
        max_flow_rate_lpm: 680,
        suction_depth_m: 12,
        dimensions_cm: '25 x 42 x 28',
        weight_kg: 32.5,
        price: 9850,
    },

    // === เพิ่มใหม่ - ปั๊มขนาดใหญ่ (7.5-10 HP) ===
    {
        id: 15,
        productCode: '1-CPM750',
        powerHP: 7.5,
        powerKW: 5.5,
        phase: 3,
        inlet_size_inch: 4,
        outlet_size_inch: 4,
        flow_rate_lpm: [300, 1200],
        head_m: [32, 20],
        max_head_m: 32,
        max_flow_rate_lpm: 1200,
        suction_depth_m: 10,
        dimensions_cm: '55 x 45 x 38',
        weight_kg: 78.5,
        price: 18500,
    },
    {
        id: 16,
        productCode: '1-CPM1000',
        powerHP: 10.0,
        powerKW: 7.5,
        phase: 3,
        inlet_size_inch: 5,
        outlet_size_inch: 5,
        flow_rate_lpm: [400, 1800],
        head_m: [38, 25],
        max_head_m: 38,
        max_flow_rate_lpm: 1800,
        suction_depth_m: 12,
        dimensions_cm: '65 x 55 x 45',
        weight_kg: 95.2,
        price: 25500,
    },

    // === เพิ่มใหม่ - ปั๊มแรงดันสูง (High Head) ===
    {
        id: 17,
        productCode: '1-HHP-300',
        powerHP: 3.0,
        powerKW: 2.2,
        phase: 1,
        inlet_size_inch: 2,
        outlet_size_inch: 1.5,
        flow_rate_lpm: [50, 300],
        head_m: [65, 35],
        max_head_m: 65,
        max_flow_rate_lpm: 300,
        suction_depth_m: 9,
        dimensions_cm: '35 x 40 x 32',
        weight_kg: 42.5,
        price: 12500,
    },
    {
        id: 18,
        productCode: '1-HHP-500',
        powerHP: 5.0,
        powerKW: 3.7,
        phase: 3,
        inlet_size_inch: 2.5,
        outlet_size_inch: 2,
        flow_rate_lpm: [80, 450],
        head_m: [85, 45],
        max_head_m: 85,
        max_flow_rate_lpm: 450,
        suction_depth_m: 10,
        dimensions_cm: '42 x 48 x 38',
        weight_kg: 58.8,
        price: 19800,
    },

    // === เพิ่มใหม่ - ปั๊มอัตราการไหลสูง (High Flow) ===
    {
        id: 19,
        productCode: '1-HFP-750',
        powerHP: 7.5,
        powerKW: 5.5,
        phase: 3,
        inlet_size_inch: 6,
        outlet_size_inch: 6,
        flow_rate_lpm: [800, 2500],
        head_m: [18, 8],
        max_head_m: 18,
        max_flow_rate_lpm: 2500,
        suction_depth_m: 8,
        dimensions_cm: '75 x 65 x 45',
        weight_kg: 125.5,
        price: 28500,
    },
    {
        id: 20,
        productCode: '1-HFP-1500',
        powerHP: 15.0,
        powerKW: 11.0,
        phase: 3,
        inlet_size_inch: 8,
        outlet_size_inch: 8,
        flow_rate_lpm: [1500, 5000],
        head_m: [15, 5],
        max_head_m: 15,
        max_flow_rate_lpm: 5000,
        suction_depth_m: 6,
        dimensions_cm: '95 x 85 x 55',
        weight_kg: 185.8,
        price: 45000,
    },

    // === เพิ่มใหม่ - ปั๊มจุ่มน้ำ (Submersible) ===
    {
        id: 21,
        productCode: '1-SUB-300',
        powerHP: 3.0,
        powerKW: 2.2,
        phase: 1,
        inlet_size_inch: 4,
        outlet_size_inch: 2,
        flow_rate_lpm: [100, 600],
        head_m: [45, 25],
        max_head_m: 45,
        max_flow_rate_lpm: 600,
        suction_depth_m: 50, // จุ่มลงไปได้ลึก
        dimensions_cm: '20 x 20 x 85', // แนวตั้ง
        weight_kg: 35.5,
        price: 15500,
    },
    {
        id: 22,
        productCode: '1-SUB-500',
        powerHP: 5.0,
        powerKW: 3.7,
        phase: 3,
        inlet_size_inch: 4,
        outlet_size_inch: 3,
        flow_rate_lpm: [200, 1000],
        head_m: [55, 30],
        max_head_m: 55,
        max_flow_rate_lpm: 1000,
        suction_depth_m: 80,
        dimensions_cm: '25 x 25 x 105',
        weight_kg: 48.8,
        price: 22500,
    },

    // === เพิ่มใหม่ - ปั๊มดันสูงพิเศษ (Ultra High Pressure) ===
    {
        id: 23,
        productCode: '1-UHP-200',
        powerHP: 2.0,
        powerKW: 1.5,
        phase: 1,
        inlet_size_inch: 1.5,
        outlet_size_inch: 1,
        flow_rate_lpm: [30, 150],
        head_m: [120, 60],
        max_head_m: 120,
        max_flow_rate_lpm: 150,
        suction_depth_m: 8,
        dimensions_cm: '28 x 35 x 40',
        weight_kg: 38.5,
        price: 16800,
    },

    // === เพิ่มใหม่ - ปั๊มประหยัดพลังงาน (Energy Saving) ===
    {
        id: 24,
        productCode: '1-ECO-400',
        powerHP: 4.0,
        powerKW: 2.8, // ประหยัดไฟ
        phase: 1,
        inlet_size_inch: 2.5,
        outlet_size_inch: 2.5,
        flow_rate_lpm: [150, 520],
        head_m: [30, 18],
        max_head_m: 30,
        max_flow_rate_lpm: 520,
        suction_depth_m: 10,
        dimensions_cm: '32 x 38 x 28',
        weight_kg: 28.5,
        price: 11200,
    },
    {
        id: 25,
        productCode: '1-ECO-750',
        powerHP: 7.5,
        powerKW: 5.0, // ประหยัดไฟ
        phase: 3,
        inlet_size_inch: 4,
        outlet_size_inch: 3.5,
        flow_rate_lpm: [300, 980],
        head_m: [35, 22],
        max_head_m: 35,
        max_flow_rate_lpm: 980,
        suction_depth_m: 12,
        dimensions_cm: '48 x 42 x 35',
        weight_kg: 52.8,
        price: 16500,
    }
];