// Pump.ts

export const PumpData = [
    {
        id: 11,
        productCode: '1-CPM075',
        brand: null,
        image: '/images/pump/1-CPM075.jpg',
        powerHP: 0.25,
        powerKW: 0.18,
        phase: 1,
        inlet_size_inch: 0.75,
        outlet_size_inch: 0.75,
        flow_rate_lpm: [10, 45],
        head_m: [18, 8],
        max_head_m: 18,
        max_flow_rate_lpm: 45,
        suction_depth_m: 8,
        dimensions_cm: '15 x 25 x 18',
        weight_kg: 8.5,
        price: 1250,
        pumpAccessory: [
            {
                id: 1,
                code: '1-CPM075-FV',
                name: 'Foot Valve',
                size: '1/2"',
                price: 150,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 2,
                code: '1-CPM075-CV',
                name: 'Check Valve',
                size: '1/2"',
                price: 300,
                description: 'ใช้เพื่อป้องกันการกลับน้ำออกจากปั๊ม',
                },
            {
                id: 3,
                code: '1-CPM075-BV',
                name: 'Ball Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 4,
                code: '1-CPM075-PG',
                name: 'Pressure Gauge',
                size: '1/2"',
                price: 100,
                description: 'ใช้วัดความดันน้ำ',
            },
            {
                id: 5,
                code: '1-CPM075-PV',
                name: 'Pressure Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 6,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 7,
                code: '1-CPM075-FI',
                name: 'Filter',
                size: '1/2"',
                price: 100,
                description: '',
            },
            {
                id: 8,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: null,
                price: 100,
                description: '',
            },
        ],
    },
    {
        id: 12,
        productCode: '1-CPM100',
        brand: 'ไชโย',
        image: null,
        powerHP: 0.33,
        powerKW: 0.25,
        phase: 1,
        inlet_size_inch: 1,
        outlet_size_inch: 1,
        flow_rate_lpm: [15, 65],
        head_m: [20, 12],
        max_head_m: 20,
        max_flow_rate_lpm: 65,
        suction_depth_m: 8,
        dimensions_cm: '16 x 28 x 20',
        weight_kg: 10.2,
        price: 1450,
        pumpAccessory: [
            // สามารถเพิ่ม property และ value ได้เอง ที่ทำไว้คือตัวอย่างการเพิ่มข้อมูลเฉยๆ สามารถเพิ่ม ลบ แก้ไขได้ตามต้องการ อาจจะไม่เหมือนกันก็ได้
            {
                id: 1,
                code: '1-CPM075-FV',
                name: 'Foot Valve',
                size: '1/2"',
                price: 150,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 2,
                code: '1-CPM075-CV',
                name: 'Check Valve',
                size: '1/2"',
                price: 300,
                description: 'ใช้เพื่อป้องกันการกลับน้ำออกจากปั๊ม',
                },
            {
                id: 3,
                code: '1-CPM075-BV',
                name: 'Ball Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 4,
                code: '1-CPM075-PG',
                name: 'Pressure Gauge',
                size: '1/2"',
                price: 100,
                description: 'ใช้วัดความดันน้ำ',
            },
            {
                id: 5,
                code: '1-CPM075-PV',
                name: 'Pressure Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 6,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 7,
                code: '1-CPM075-FI',
                name: 'Filter',
                size: '1/2"',
                price: 100,
                description: '',
            },
            {
                id: 8,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: null,
                price: 100,
                description: '',
            },
            // สามารถเพิ่มได้เอง เพิ่มข้อมูลตามที่ต้องการ
            {
                id: 9, 
                code: '', //unique
                name: '',
                size: null,
                price: null,
                description: '',
                // สามารถเพิ่ม property และ value ได้เอง
            },
        ],
    },
    {
        id: 4,
        productCode: null,
        brand: null,
        image: null,
        powerHP: null,
        powerKW: null,
        phase: null,
        inlet_size_inch: null,
        outlet_size_inch: null,
        flow_rate_lpm: null,
        head_m: null,
        max_head_m: null,
        max_flow_rate_lpm: null,
        suction_depth_m: null,
        dimensions_cm: null,
        weight_kg: null,
        price: null,    
        pumpAccessory: [],
    },
    {
        id: 5,
        productCode: '1-CPM158',
        brand: 'ไชโย',
        image: '/images/pump/1-CPM158.jpg',
        powerHP: 1.0,
        powerKW: 0.75,
        phase: 1,
        inlet_size_inch: 1,
        outlet_size_inch: 1,
        flow_rate_lpm: [30, 120],
        head_m: [28, 18],
        max_head_m: 28,
        max_flow_rate_lpm: 120,
        suction_depth_m: 9,
        dimensions_cm: '20 x 32 x 24',
        weight_kg: 15.8,
        price: 2675,
        pumpAccessory: [
            {
                id: 1,
                code: '1-CPM075-FV',
                name: 'Foot Valve',
                size: '1/2"',
                price: 150,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 2,
                code: '1-CPM075-CV',
                name: 'Check Valve',
                size: '1/2"',
                price: 300,
                description: 'ใช้เพื่อป้องกันการกลับน้ำออกจากปั๊ม',
                },
            {
                id: 3,
                code: '1-CPM075-BV',
                name: 'Ball Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 4,
                code: '1-CPM075-PG',
                name: 'Pressure Gauge',
                size: '1/2"',
                price: 100,
                description: 'ใช้วัดความดันน้ำ',
            },
            {
                id: 5,
                code: '1-CPM075-PV',
                name: 'Pressure Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 6,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 7,
                code: '1-CPM075-FI',
                name: 'Filter',
                size: '1/2"',
                price: 100,
                description: '',
            },
            {
                id: 8,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: null,
                price: 100,
                description: '',
            },
            // สามารถเพิ่มได้เอง เพิ่มข้อมูลตามที่ต้องการ
            {
                id: 9,
                code: '', //unique
                name: '',
                size: null,
                price: null,
                description: '',
            },
        ],
    },

    {
        id: 1,
        productCode: '1-CJP-K160',
        brand: 'แชมป์',
        image: '/images/pump/1-CJP-K160.jpg',
        powerHP: 1.5,
        powerKW: 1.1,
        phase: 1,
        inlet_size_inch: 1.5,
        outlet_size_inch: 1.5,
        flow_rate_lpm: [50, 280],
        head_m: [32, 15],
        max_head_m: 32,
        max_flow_rate_lpm: 280,
        suction_depth_m: 10,
        dimensions_cm: '19 x 35 x 25',
        weight_kg: 19.48,
        price: 6420,
        pumpAccessory: [
            // สามารถเพิ่ม property และ value ได้เอง ที่ทำไว้คือตัวอย่างการเพิ่มข้อมูลเฉยๆ สามารถเพิ่ม ลบ แก้ไขได้ตามต้องการ อาจจะไม่เหมือนกันก็ได้
            {
                id: 1,
                code: '1-CPM075-FV',
                name: 'Foot Valve',
                size: '1/2"',
                price: 150,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 2,
                code: '1-CPM075-CV',
                name: 'Check Valve',
                size: '1/2"',
                price: 300,
                description: 'ใช้เพื่อป้องกันการกลับน้ำออกจากปั๊ม',
                },
            {
                id: 3,
                code: '1-CPM075-BV',
                name: 'Ball Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 4,
                code: '1-CPM075-PG',
                name: 'Pressure Gauge',
                size: '1/2"',
                price: 100,
                description: 'ใช้วัดความดันน้ำ',
            },
            {
                id: 5,
                code: '1-CPM075-PV',
                name: 'Pressure Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 6,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            
            // สามารถเพิ่มได้เอง เพิ่มข้อมูลตามที่ต้องการ
            {
                id: 7, 
                code: '', //unique
                name: '',
                size: null,
                price: null,
                description: '',
                // สามารถเพิ่ม property และ value ได้เอง
            },
        ],
    },
    {
        id: 6,
        productCode: '1-CPM200',
        brand: 'แชมป์',
        image: '/images/pump/1-CPM200.jpg',
        powerHP: 2.0,
        powerKW: 1.5,
        phase: 1,
        inlet_size_inch: 2,
        outlet_size_inch: 2,
        flow_rate_lpm: [80, 400],
        head_m: [35, 20],
        max_head_m: 35,
        max_flow_rate_lpm: 400,
        suction_depth_m: 9,
        dimensions_cm: '22 x 38 x 28',
        weight_kg: 22.5,
        price: 3745,
        pumpAccessory: [
            // สามารถเพิ่ม property และ value ได้เอง ที่ทำไว้คือตัวอย่างการเพิ่มข้อมูลเฉยๆ สามารถเพิ่ม ลบ แก้ไขได้ตามต้องการ อาจจะไม่เหมือนกันก็ได้
            {
                id: 1,
                code: '1-CPM075-FV',
                name: 'Foot Valve',
                size: '2"',
                price: 150,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 2,
                code: '1-CPM075-CV',
                name: 'Check Valve',
                size: '2"',
                price: 300,
                description: 'ใช้เพื่อป้องกันการกลับน้ำออกจากปั๊ม',
                },
            {
                id: 3,
                code: '1-CPM075-BV',
                name: 'Ball Valve',
                size: '2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 4,
                code: '1-CPM075-PG',
                name: 'Pressure Gauge',
                size: '1"',
                price: 100,
                description: 'ใช้วัดความดันน้ำ',
            },
            {
                id: 5,
                code: '1-CPM075-PV',
                name: 'Pressure Valve',
                size: '3"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 6,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 7,
                code: '1-CPM075-FI',
                name: 'Filter',
                size: '4"',
                price: 100,
                description: '',
            },
            {
                id: 8,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: null,
                price: 100,
                description: '',
            },
            // สามารถเพิ่มได้เอง เพิ่มข้อมูลตามที่ต้องการ
            {
                id: 9, 
                code: '', //unique
                name: '',
                size: null,
                price: null,
                description: '',
                // สามารถเพิ่ม property และ value ได้เอง
            },
        ],
    },
    {
        id: 2,
        productCode: '1-CJP-K407',
        brand: 'แชมป์',
        image: '/images/pump/1-CJP-K407.jpg',
        powerHP: 2,
        powerKW: 1.5,
        phase: 1,
        inlet_size_inch: 2,
        outlet_size_inch: 2,
        flow_rate_lpm: [100, 450],
        head_m: [30, 18],
        max_head_m: 30,
        max_flow_rate_lpm: 450,
        suction_depth_m: 10,
        dimensions_cm: '19 x 35 x 25',
        weight_kg: 19.5,
        price: 7000,
        pumpAccessory: [
            // สามารถเพิ่ม property และ value ได้เอง ที่ทำไว้คือตัวอย่างการเพิ่มข้อมูลเฉยๆ สามารถเพิ่ม ลบ แก้ไขได้ตามต้องการ อาจจะไม่เหมือนกันก็ได้
            {
                id: 1,
                code: '1-CPM075-FV',
                name: 'Foot Valve',
                size: '1/2"',
                price: 150,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 2,
                code: '1-CPM075-CV',
                name: 'Check Valve',
                size: '1/2"',
                price: 300,
                description: 'ใช้เพื่อป้องกันการกลับน้ำออกจากปั๊ม',
                },
            {
                id: 3,
                code: '1-CPM075-BV',
                name: 'Ball Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 4,
                code: '1-CPM075-PG',
                name: 'Pressure Gauge',
                size: '1/2"',
                price: 100,
                description: 'ใช้วัดความดันน้ำ',
            },
            {
                id: 5,
                code: '1-CPM075-PV',
                name: 'Pressure Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 6,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 7,
                code: '1-CPM075-FI',
                name: 'Filter',
                size: '1/2"',
                price: 100,
                description: '',
            },
            {
                id: 8,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: null,
                price: 100,
                description: '',
            },
            // สามารถเพิ่มได้เอง เพิ่มข้อมูลตามที่ต้องการ
            {
                id: 9, 
                code: '', //unique
                name: '',
                size: null,
                price: null,
                description: '',
                // สามารถเพิ่ม property และ value ได้เอง
            },
        ],
    },
    
    {
        id: 7,
        productCode: '1-CPM300',
        brand: 'แชมป์',
        image: '/images/pump/1-CPM300.jpg',
        powerHP: 3.0,
        powerKW: 2.2,
        phase: 1,
        inlet_size_inch: 2,
        outlet_size_inch: 2,
        flow_rate_lpm: [150, 600],
        head_m: [38, 22],
        max_head_m: 38,
        max_flow_rate_lpm: 600,
        suction_depth_m: 9,
        dimensions_cm: '24 x 40 x 30',
        weight_kg: 28.5,
        price: 5510,
        pumpAccessory: [],
    },

    {
        id: 17,
        productCode: '1-HHP-300',
        brand: 'แชมป์',
        image: '/images/pump/1-HHP-300.jpg',
        powerHP: 3.0,
        powerKW: 2.2,
        phase: 1,
        inlet_size_inch: 2,
        outlet_size_inch: 1.5,
        flow_rate_lpm: [80, 350],
        head_m: [70, 40],
        max_head_m: 70,
        max_flow_rate_lpm: 350,
        suction_depth_m: 9,
        dimensions_cm: '35 x 40 x 32',
        weight_kg: 42.5,
        price: 12500,
        pumpAccessory: [
            // สามารถเพิ่ม property และ value ได้เอง ที่ทำไว้คือตัวอย่างการเพิ่มข้อมูลเฉยๆ สามารถเพิ่ม ลบ แก้ไขได้ตามต้องการ อาจจะไม่เหมือนกันก็ได้
            {
                id: 1,
                code: '1-CPM075-FV',
                brand: 'แชมป์',
                name: 'Foot Valve',
                size: '1/2"',
                price: 150,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 2,
                code: '1-CPM075-CV',
                brand: 'แชมป์',
                name: 'Check Valve',
                size: '1/2"',
                price: 300,
                description: 'ใช้เพื่อป้องกันการกลับน้ำออกจากปั๊ม',
                },
            {
                id: 3,
                code: '1-CPM075-BV',
                name: 'Ball Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 4,
                code: '1-CPM075-PG',
                brand: 'แชมป์',
                name: 'Pressure Gauge',
                size: '',
                price: 100,
                description: '',
            },
            {
                id: 5,
                code: '1-CPM075-PV',
                name: 'Pressure Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 6,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 7,
                code: '1-CPM075-FI',
                name: 'Filter',
                size: '1/2"',
                price: 100,
                description: '',
            },
            {
                id: 8,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: null,
                price: 100,
                description: '',
            },
            // สามารถเพิ่มได้เอง เพิ่มข้อมูลตามที่ต้องการ
            {
                id: 9, 
                code: '', //unique
                name: '',
                size: null,
                price: null,
                description: '',
                // สามารถเพิ่ม property และ value ได้เอง
            },
        ],
    },
    {
        id: 24,
        productCode: '1-ECO-400',
        brand: 'ไชโย',
        image: '/images/pump/1-ECO-400.jpg',
        powerHP: 4.0,
        powerKW: 2.8,
        phase: 1,
        inlet_size_inch: 2.5,
        outlet_size_inch: 2.5,
        flow_rate_lpm: [200, 650],
        head_m: [45, 25],
        max_head_m: 45,
        max_flow_rate_lpm: 650,
        suction_depth_m: 10,
        dimensions_cm: '32 x 38 x 28',
        weight_kg: 28.5,
        price: 11200,
        pumpAccessory: [],
    },
    {
        id: 14,
        productCode: '1-CJP-K750',
        brand: 'ไชโย',
        image: '/images/pump/1-CJP-K750.jpg',
        powerHP: 4.0,
        powerKW: 3.0,
        phase: 1,
        inlet_size_inch: 2.5,
        outlet_size_inch: 2.5,
        flow_rate_lpm: [250, 750],
        head_m: [48, 28],
        max_head_m: 48,
        max_flow_rate_lpm: 750,
        suction_depth_m: 12,
        dimensions_cm: '25 x 42 x 28',
        weight_kg: 32.5,
        price: 9850,
        pumpAccessory: [],
    },
    {
        id: 13,
        productCode: '1-CPM500',
        brand: 'ไชโย',
        image: '/images/pump/1-CPM500.jpg',
        powerHP: 5.0,
        powerKW: 3.7,
        phase: 1,
        inlet_size_inch: 3,
        outlet_size_inch: 3,
        flow_rate_lpm: [300, 900],
        head_m: [50, 30],
        max_head_m: 50,
        max_flow_rate_lpm: 900,
        suction_depth_m: 9,
        dimensions_cm: '45 x 35 x 30',
        weight_kg: 45.8,
        price: 8950,
        pumpAccessory: [],
    },
    {
        id: 18,
        productCode: '1-HHP-500',
        brand: 'ไชโย',
        image: '/images/pump/1-HHP-500.jpg',
        powerHP: 5.0,
        powerKW: 3.7,
        phase: 3,
        inlet_size_inch: 2.5,
        outlet_size_inch: 2,
        flow_rate_lpm: [200, 550],
        head_m: [85, 55],
        max_head_m: 85,
        max_flow_rate_lpm: 550,
        suction_depth_m: 10,
        dimensions_cm: '42 x 48 x 38',
        weight_kg: 58.8,
        price: 19800,
        pumpAccessory: [
            // สามารถเพิ่ม property และ value ได้เอง ที่ทำไว้คือตัวอย่างการเพิ่มข้อมูลเฉยๆ สามารถเพิ่ม ลบ แก้ไขได้ตามต้องการ อาจจะไม่เหมือนกันก็ได้
            {
                id: 1,
                code: '1-CPM075-FV',
                name: 'Foot Valve',
                size: '1/2"',
                price: 150,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 2,
                code: '1-CPM075-CV',
                name: 'Check Valve',
                size: '1/2"',
                price: 300,
                description: 'ใช้เพื่อป้องกันการกลับน้ำออกจากปั๊ม',
                },
            {
                id: 3,
                code: '1-CPM075-BV',
                name: 'Ball Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 4,
                code: '1-CPM075-PG',
                name: 'Pressure Gauge',
                size: '1/2"',
                price: 100,
                description: 'ใช้วัดความดันน้ำ',
            },
            {
                id: 5,
                code: '1-CPM075-PV',
                name: 'Pressure Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 6,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: '1/2"',
                price: 100,
                description: 'ใช้ปิดปล่อยน้ำออกจากปั๊ม',
            },
            {
                id: 7,
                code: '1-CPM075-FI',
                name: 'Filter',
                size: '1/2"',
                price: 100,
                description: '',
            },
            {
                id: 8,
                code: '1-CPM075-PRV',
                name: 'Pressure Relief Valve',
                size: null,
                price: 100,
                description: '',
            },
            // สามารถเพิ่มได้เอง เพิ่มข้อมูลตามที่ต้องการ
            {
                id: 9, 
                code: '', //unique
                name: '',
                size: null,
                price: null,
                description: '',
                // สามารถเพิ่ม property และ value ได้เอง
            },
        ],
    },
];
