// // C:\webchaiyo\Waterapp\resources\js\pages\product\Sprinkler.js
// export const SprinklerData = [
//     {
//         id: 1,
//         productCode: '318',
//         name: 'สปริงเกอร์ สายฝน เกลียวใน 3/4" x 1/2"',
//         waterVolumeLitersPerHour: [4.67, 7.67],
//         radiusMeters: [2.5, 5],
//         pressureBar: [0.5, 3],
//         price: 4.5,
//     },
//     {
//         id: 2,
//         productCode: '318-D',
//         name: 'สปริงเกอร์ สายฝน 3 in 1 เกลียวใน 3/4" x 1/2"',
//         waterVolumeLitersPerHour: [4.67, 7.67],
//         radiusMeters: [2.5, 5],
//         pressureBar: [0.5, 3],
//         price: 6.0,
//     },
//     {
//         id: 3,
//         productCode: '318-T',
//         name: 'สปริงเกอร์ สายฝน 2 in 1 หัวปะทะ เกลียวใน 3/4" x 1/2"',
//         waterVolumeLitersPerHour: [4.67, 7.67],
//         radiusMeters: [2.5, 5],
//         pressureBar: [0.5, 3],
//         price: 6.0,
//     },
//     {
//         id: 4,
//         productCode: '319-C',
//         name: 'สปริงเกอร์ สายฝน 3 in 1 ฝาครอบ 1/2"',
//         waterVolumeLitersPerHour: [4.67, 7.67],
//         radiusMeters: [2.5, 5],
//         pressureBar: [0.5, 3],
//         price: 6.0,
//     },
//     {
//         id: 5,
//         productCode: '319-CY2',
//         name: 'สปริงเกอร์ สายฝน 3 in 1 ฝาครอบ 1/2"',
//         waterVolumeLitersPerHour: [4.67, 7.67],
//         radiusMeters: [2.5, 5],
//         pressureBar: [0.5, 3],
//         price: 4.5,
//     },
//     {
//         id: 6,
//         productCode: '318-11',
//         name: 'สปริงเกอร์ พร้อมขาปักสายยาง 1/2" x 5/8" x 3/4"',
//         waterVolumeLitersPerHour: [4.67, 7.67],
//         radiusMeters: [2.5, 5],
//         pressureBar: [0.5, 3],
//         price: 22.0,
//     },
//     {
//         id: 7,
//         productCode: '300B',
//         name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าเกลียวใน 3/4"x1/2"',
//         waterVolumeLitersPerHour: [8.33, 15.0],
//         radiusMeters: [4, 6],
//         pressureBar: [0.5, 3],
//         price: 6.0,
//     },
//     {
//         id: 8,
//         productCode: '300BR',
//         name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าเกลียวใน หมุนรอบตัว 3/4"x1/2"',
//         waterVolumeLitersPerHour: '8.33-15.00',
//         radiusMeters: '4-6',
//         pressureBar: '0.5-3',
//         price: 8.5,
//     },
//     {
//         id: 9,
//         productCode: '300B-C1',
//         name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าหมุนรอบตัว+ฝาครอบ 1/2"',
//         waterVolumeLitersPerHour: [8.33, 15.0],
//         radiusMeters: [4, 6],
//         pressureBar: [0.5, 3],
//         price: 9.0,
//     },
//     {
//         id: 10,
//         productCode: '300B-C2',
//         name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าหมุนรอบตัว+ฝาครอบ 3/4"',
//         waterVolumeLitersPerHour: [8.33, 15.0],
//         radiusMeters: [4, 6],
//         pressureBar: [0.5, 3],
//         price: 10.0,
//     },
//     {
//         id: 11,
//         productCode: '300B-V1',
//         name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าพร้อมวาล์ว PVC 1/2"',
//         waterVolumeLitersPerHour: [8.33, 15.0],
//         radiusMeters: [4, 6],
//         pressureBar: [0.5, 3],
//         price: 13.0,
//     },
//     {
//         id: 12,
//         productCode: '300B-V2',
//         name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าพร้อมวาล์ว PVC 3/4"',
//         waterVolumeLitersPerHour: [8.33, 15.0],
//         radiusMeters: [4, 6],
//         pressureBar: [0.5, 3],
//         price: 15.5,
//     },
//     {
//         id: 13,
//         productCode: '300B-V3',
//         name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าพร้อมวาล์ว PE 16-20 มม.',
//         waterVolumeLitersPerHour: [8.33, 15.0],
//         radiusMeters: [4, 6],
//         pressureBar: [0.5, 3],
//         price: 13.0,
//     },
//     {
//         id: 14,
//         productCode: '300B-V4',
//         name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าพร้อมวาล์ว PE 25 มม.',
//         waterVolumeLitersPerHour: [8.33, 15.0],
//         radiusMeters: [4, 6],
//         pressureBar: [0.5, 3],
//         price: 14.0,
//     },
//     {
//         id: 15,
//         productCode: '315',
//         name: 'สปริงเกอร์ แบบแนน รุ่น 5 มม.เกลียวนอก 3/4"พร้อมหัวฉีดน้ำ',
//         waterVolumeLitersPerHour: [12.5, 41.7],
//         radiusMeters: [6, 15],
//         pressureBar: [0.5, 3],
//         price: 140.0,
//     },
//     {
//         id: 16,
//         productCode: '316',
//         name: 'สปริงเกอร์ แบบแนน รุ่น 5 มม.เกลียวใน 1"พร้อมหัวฉีดน้ำ',
//         waterVolumeLitersPerHour: [12.5, 41.7],
//         radiusMeters: [6, 15],
//         pressureBar: [0.5, 3],
//         price: 150.0,
//     },
//     {
//         id: 17,
//         productCode: '315-1',
//         name: 'สปริงเกอร์ แบบแนน รุ่น 5 มม.พร้อมขาปักสายยาง 1/2"x5/8"x3/4" พร้อมหัวฉีดน้ำ',
//         waterVolumeLitersPerHour: [12.5, 41.7],
//         radiusMeters: [6, 15],
//         pressureBar: [0.5, 3],
//         price: 160.0,
//     },
//     {
//         id: 18,
//         productCode: '313',
//         name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.เกลียวนอก 1/2"พร้อมหัวฉีดน้ำ',
//         waterVolumeLitersPerHour: [9.5, 20.0],
//         radiusMeters: [7, 12],
//         pressureBar: [0.5, 4],
//         price: 43.0,
//     },
//     {
//         id: 19,
//         productCode: '313-B',
//         name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.เกลียวนอก 3/4"พร้อมหัวฉีดน้ำ',
//         waterVolumeLitersPerHour: [9.5, 20.0],
//         radiusMeters: [7, 12],
//         pressureBar: [0.5, 4],
//         price: 53.0,
//     },
//     {
//         id: 20,
//         productCode: '314',
//         name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.เกลียวใน 3/4"พร้อมหัวฉีดน้ำ',
//         waterVolumeLitersPerHour: [9.5, 20.0],
//         radiusMeters: [7, 12],
//         pressureBar: [0.5, 4],
//         price: 53.0,
//     },
//     {
//         id: 21,
//         productCode: '313-C',
//         name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.หมุนรอบตัว ฝาครอบ PVC 1/2"',
//         waterVolumeLitersPerHour: [9.5, 20.0],
//         radiusMeters: [7, 12],
//         pressureBar: [0.5, 4],
//         price: 43.0,
//     },
//     {
//         id: 22,
//         productCode: '313-11',
//         name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.พร้อมขาปักสายยาง 1/2"x5/8"x3/4" พร้อมหัวฉีดน้ำ',
//         waterVolumeLitersPerHour: [9.5, 20.0],
//         radiusMeters: [7, 12],
//         pressureBar: [0.5, 4],
//         price: 80.0,
//     },
// ];
export const SprinklerData = [
    // === ข้อมูลเดิม - สปริงเกอร์สายฝน ===
    {
        id: 1,
        productCode: '318',
        name: 'สปริงเกอร์ สายฝน เกลียวใน 3/4" x 1/2"',
        waterVolumeLitersPerHour: [4.67, 7.67],
        radiusMeters: [2.5, 5],
        pressureBar: [0.5, 3],
        price: 4.5,
    },
    {
        id: 2,
        productCode: '318-D',
        name: 'สปริงเกอร์ สายฝน 3 in 1 เกลียวใน 3/4" x 1/2"',
        waterVolumeLitersPerHour: [4.67, 7.67],
        radiusMeters: [2.5, 5],
        pressureBar: [0.5, 3],
        price: 6.0,
    },
    {
        id: 3,
        productCode: '318-T',
        name: 'สปริงเกอร์ สายฝน 2 in 1 หัวปะทะ เกลียวใน 3/4" x 1/2"',
        waterVolumeLitersPerHour: [4.67, 7.67],
        radiusMeters: [2.5, 5],
        pressureBar: [0.5, 3],
        price: 6.0,
    },
    {
        id: 4,
        productCode: '319-C',
        name: 'สปริงเกอร์ สายฝน 3 in 1 ฝาครอบ 1/2"',
        waterVolumeLitersPerHour: [4.67, 7.67],
        radiusMeters: [2.5, 5],
        pressureBar: [0.5, 3],
        price: 6.0,
    },
    {
        id: 5,
        productCode: '319-CY2',
        name: 'สปริงเกอร์ สายฝน 3 in 1 ฝาครอบ 1/2"',
        waterVolumeLitersPerHour: [4.67, 7.67],
        radiusMeters: [2.5, 5],
        pressureBar: [0.5, 3],
        price: 4.5,
    },
    {
        id: 6,
        productCode: '318-11',
        name: 'สปริงเกอร์ พร้อมขาปักสายยาง 1/2" x 5/8" x 3/4"',
        waterVolumeLitersPerHour: [4.67, 7.67],
        radiusMeters: [2.5, 5],
        pressureBar: [0.5, 3],
        price: 22.0,
    },

    // === ข้อมูลเดิม - สปริงเกอร์ใบน้ำ ===
    {
        id: 7,
        productCode: '300B',
        name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าเกลียวใน 3/4"x1/2"',
        waterVolumeLitersPerHour: [8.33, 15.0],
        radiusMeters: [4, 6],
        pressureBar: [0.5, 3],
        price: 6.0,
    },
    {
        id: 8,
        productCode: '300BR',
        name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าเกลียวใน หมุนรอบตัว 3/4"x1/2"',
        waterVolumeLitersPerHour: [8.33, 15.0],
        radiusMeters: [4, 6],
        pressureBar: [0.5, 3],
        price: 8.5,
    },
    {
        id: 9,
        productCode: '300B-C1',
        name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าหมุนรอบตัว+ฝาครอบ 1/2"',
        waterVolumeLitersPerHour: [8.33, 15.0],
        radiusMeters: [4, 6],
        pressureBar: [0.5, 3],
        price: 9.0,
    },
    {
        id: 10,
        productCode: '300B-C2',
        name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าหมุนรอบตัว+ฝาครอบ 3/4"',
        waterVolumeLitersPerHour: [8.33, 15.0],
        radiusMeters: [4, 6],
        pressureBar: [0.5, 3],
        price: 10.0,
    },
    {
        id: 11,
        productCode: '300B-V1',
        name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าพร้อมวาล์ว PVC 1/2"',
        waterVolumeLitersPerHour: [8.33, 15.0],
        radiusMeters: [4, 6],
        pressureBar: [0.5, 3],
        price: 13.0,
    },
    {
        id: 12,
        productCode: '300B-V2',
        name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าพร้อมวาล์ว PVC 3/4"',
        waterVolumeLitersPerHour: [8.33, 15.0],
        radiusMeters: [4, 6],
        pressureBar: [0.5, 3],
        price: 15.5,
    },
    {
        id: 13,
        productCode: '300B-V3',
        name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าพร้อมวาล์ว PE 16-20 มม.',
        waterVolumeLitersPerHour: [8.33, 15.0],
        radiusMeters: [4, 6],
        pressureBar: [0.5, 3],
        price: 13.0,
    },
    {
        id: 14,
        productCode: '300B-V4',
        name: 'สปริงเกอร์ ใบน้ำ 2 ชั้น สีฟ้าพร้อมวาล์ว PE 25 มม.',
        waterVolumeLitersPerHour: [8.33, 15.0],
        radiusMeters: [4, 6],
        pressureBar: [0.5, 3],
        price: 14.0,
    },

    // === ข้อมูลเดิม - สปริงเกอร์แบบแนน ===
    {
        id: 15,
        productCode: '315',
        name: 'สปริงเกอร์ แบบแนน รุ่น 5 มม.เกลียวนอก 3/4"พร้อมหัวฉีดน้ำ',
        waterVolumeLitersPerHour: [12.5, 41.7],
        radiusMeters: [6, 15],
        pressureBar: [0.5, 3],
        price: 140.0,
    },
    {
        id: 16,
        productCode: '316',
        name: 'สปริงเกอร์ แบบแนน รุ่น 5 มม.เกลียวใน 1"พร้อมหัวฉีดน้ำ',
        waterVolumeLitersPerHour: [12.5, 41.7],
        radiusMeters: [6, 15],
        pressureBar: [0.5, 3],
        price: 150.0,
    },
    {
        id: 17,
        productCode: '315-1',
        name: 'สปริงเกอร์ แบบแนน รุ่น 5 มม.พร้อมขาปักสายยาง 1/2"x5/8"x3/4" พร้อมหัวฉีดน้ำ',
        waterVolumeLitersPerHour: [12.5, 41.7],
        radiusMeters: [6, 15],
        pressureBar: [0.5, 3],
        price: 160.0,
    },
    {
        id: 18,
        productCode: '313',
        name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.เกลียวนอก 1/2"พร้อมหัวฉีดน้ำ',
        waterVolumeLitersPerHour: [9.5, 20.0],
        radiusMeters: [7, 12],
        pressureBar: [0.5, 4],
        price: 43.0,
    },
    {
        id: 19,
        productCode: '313-B',
        name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.เกลียวนอก 3/4"พร้อมหัวฉีดน้ำ',
        waterVolumeLitersPerHour: [9.5, 20.0],
        radiusMeters: [7, 12],
        pressureBar: [0.5, 4],
        price: 53.0,
    },
    {
        id: 20,
        productCode: '314',
        name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.เกลียวใน 3/4"พร้อมหัวฉีดน้ำ',
        waterVolumeLitersPerHour: [9.5, 20.0],
        radiusMeters: [7, 12],
        pressureBar: [0.5, 4],
        price: 53.0,
    },
    {
        id: 21,
        productCode: '313-C',
        name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.หมุนรอบตัว ฝาครอบ PVC 1/2"',
        waterVolumeLitersPerHour: [9.5, 20.0],
        radiusMeters: [7, 12],
        pressureBar: [0.5, 4],
        price: 43.0,
    },
    {
        id: 22,
        productCode: '313-11',
        name: 'สปริงเกอร์ แบบแนน รุ่น 3 มม.พร้อมขาปักสายยาง 1/2"x5/8"x3/4" พร้อมหัวฉีดน้ำ',
        waterVolumeLitersPerHour: [9.5, 20.0],
        radiusMeters: [7, 12],
        pressureBar: [0.5, 4],
        price: 80.0,
    },

    // === เพิ่มใหม่ - ไมโครสปริงเกอร์ (ขนาดเล็ก) ===
    {
        id: 23,
        productCode: 'MICRO-01',
        name: 'ไมโครสปริงเกอร์ 180° เกลียว 1/4"',
        waterVolumeLitersPerHour: [0.8, 2.5],
        radiusMeters: [0.5, 1.5],
        pressureBar: [0.3, 2],
        price: 12.0,
    },
    {
        id: 24,
        productCode: 'MICRO-02',
        name: 'ไมโครสปริงเกอร์ 360° เกลียว 1/4"',
        waterVolumeLitersPerHour: [1.2, 3.5],
        radiusMeters: [0.8, 2],
        pressureBar: [0.3, 2],
        price: 14.0,
    },
    {
        id: 25,
        productCode: 'MICRO-03',
        name: 'ไมโครสปริงเกอร์ ปรับได้ เกลียว 1/4"',
        waterVolumeLitersPerHour: [0.5, 4.0],
        radiusMeters: [0.3, 2.5],
        pressureBar: [0.3, 2.5],
        price: 18.0,
    },

    // === เพิ่มใหม่ - ดริปเปอร์ ===
    {
        id: 26,
        productCode: 'DRIP-01',
        name: 'ดริปเปอร์ แรงดันชดเชย 2 L/h',
        waterVolumeLitersPerHour: [2.0, 2.0],
        radiusMeters: [0.3, 0.5],
        pressureBar: [0.5, 4],
        price: 3.5,
    },
    {
        id: 27,
        productCode: 'DRIP-02',
        name: 'ดริปเปอร์ แรงดันชดเชย 4 L/h',
        waterVolumeLitersPerHour: [4.0, 4.0],
        radiusMeters: [0.3, 0.5],
        pressureBar: [0.5, 4],
        price: 3.8,
    },
    {
        id: 28,
        productCode: 'DRIP-03',
        name: 'ดริปเปอร์ แรงดันชดเชย 8 L/h',
        waterVolumeLitersPerHour: [8.0, 8.0],
        radiusMeters: [0.5, 0.8],
        pressureBar: [0.5, 4],
        price: 4.2,
    },
    {
        id: 29,
        productCode: 'DRIP-04',
        name: 'ดริปเปอร์ ปรับได้ 0-20 L/h',
        waterVolumeLitersPerHour: [0, 20.0],
        radiusMeters: [0.2, 1.0],
        pressureBar: [0.3, 3],
        price: 8.5,
    },

    // === เพิ่มใหม่ - สปริงเกอร์ขนาดกลาง ===
    {
        id: 30,
        productCode: 'MED-01',
        name: 'สปริงเกอร์ ขนาดกลาง 1" หมุนรอบตัว',
        waterVolumeLitersPerHour: [25, 60],
        radiusMeters: [8, 18],
        pressureBar: [1, 4],
        price: 85.0,
    },
    {
        id: 31,
        productCode: 'MED-02',
        name: 'สปริงเกอร์ ขนาดกลาง 1.25" หมุนรอบตัว',
        waterVolumeLitersPerHour: [35, 85],
        radiusMeters: [10, 22],
        pressureBar: [1, 4],
        price: 120.0,
    },
    {
        id: 32,
        productCode: 'MED-03',
        name: 'สปริงเกอร์ ขนาดกลาง แบบปรับได้ 1"',
        waterVolumeLitersPerHour: [15, 75],
        radiusMeters: [6, 20],
        pressureBar: [0.8, 4],
        price: 95.0,
    },

    // === เพิ่มใหม่ - สปริงเกอร์ขนาดใหญ่ ===
    {
        id: 33,
        productCode: 'BIG-01',
        name: 'สปริงเกอร์ ขนาดใหญ่ 1.5" แรงดันสูง',
        waterVolumeLitersPerHour: [80, 200],
        radiusMeters: [15, 35],
        pressureBar: [2, 6],
        price: 280.0,
    },
    {
        id: 34,
        productCode: 'BIG-02',
        name: 'สปริงเกอร์ ขนาดใหญ่ 2" แรงดันสูง',
        waterVolumeLitersPerHour: [150, 400],
        radiusMeters: [20, 45],
        pressureBar: [2.5, 6],
        price: 450.0,
    },
    {
        id: 35,
        productCode: 'BIG-03',
        name: 'สปริงเกอร์ อุตสาหกรรม 2.5" แรงดันสูง',
        waterVolumeLitersPerHour: [300, 800],
        radiusMeters: [25, 60],
        pressureBar: [3, 8],
        price: 850.0,
    },
    {
        id: 36,
        productCode: 'BIG-04',
        name: 'สปริงเกอร์ อุตสาหกรรม 3" แรงดันสูงพิเศษ',
        waterVolumeLitersPerHour: [500, 1500],
        radiusMeters: [30, 80],
        pressureBar: [4, 10],
        price: 1500.0,
    },

    // === เพิ่มใหม่ - มิสท์เนอร์ (ฝอย) ===
    {
        id: 37,
        productCode: 'MIST-01',
        name: 'มิสท์เนอร์ ฝอยละเอียด 1/4"',
        waterVolumeLitersPerHour: [1.5, 5.0],
        radiusMeters: [1, 3],
        pressureBar: [1.5, 5],
        price: 25.0,
    },
    {
        id: 38,
        productCode: 'MIST-02',
        name: 'มิสท์เนอร์ ฝอยละเอียด 3/8"',
        waterVolumeLitersPerHour: [3.0, 8.0],
        radiusMeters: [1.5, 4],
        pressureBar: [1.5, 5],
        price: 32.0,
    },
    {
        id: 39,
        productCode: 'MIST-03',
        name: 'มิสท์เนอร์ แรงดันสูง 1/2"',
        waterVolumeLitersPerHour: [5.0, 15.0],
        radiusMeters: [2, 6],
        pressureBar: [2, 8],
        price: 65.0,
    },

    // === เพิ่มใหม่ - สปริงเกอร์แรงดันต่ำ ===
    {
        id: 40,
        productCode: 'LOW-01',
        name: 'สปริงเกอร์ แรงดันต่ำ 3/4" หัวใหญ่',
        waterVolumeLitersPerHour: [15, 35],
        radiusMeters: [5, 12],
        pressureBar: [0.2, 1.5],
        price: 35.0,
    },
    {
        id: 41,
        productCode: 'LOW-02',
        name: 'สปริงเกอร์ แรงดันต่ำ 1" หัวใหญ่พิเศษ',
        waterVolumeLitersPerHour: [25, 55],
        radiusMeters: [8, 15],
        pressureBar: [0.2, 1.5],
        price: 48.0,
    },

    // === เพิ่มใหม่ - สปริงเกอร์พิเศษ ===
    {
        id: 42,
        productCode: 'SPEC-01',
        name: 'สปริงเกอร์ แบบพัลส์ ประหยัดน้ำ 3/4"',
        waterVolumeLitersPerHour: [8, 25],
        radiusMeters: [4, 10],
        pressureBar: [0.8, 3],
        price: 85.0,
    },
    {
        id: 43,
        productCode: 'SPEC-02',
        name: 'สปริงเกอร์ แบบมัลติเจ็ท 1"',
        waterVolumeLitersPerHour: [20, 45],
        radiusMeters: [6, 14],
        pressureBar: [1, 4],
        price: 125.0,
    },
    {
        id: 44,
        productCode: 'SPEC-03',
        name: 'สปริงเกอร์ แบบโซน่า 360° ปรับได้',
        waterVolumeLitersPerHour: [12, 40],
        radiusMeters: [3, 12],
        pressureBar: [0.5, 3.5],
        price: 95.0,
    },

    // === เพิ่มใหม่ - สปริงเกอร์สำหรับไม้ผล ===
    {
        id: 45,
        productCode: 'FRUIT-01',
        name: 'สปริงเกอร์ สำหรับทุเรียน/มังคุด 1"',
        waterVolumeLitersPerHour: [40, 120],
        radiusMeters: [8, 25],
        pressureBar: [1.5, 5],
        price: 180.0,
    },
    {
        id: 46,
        productCode: 'FRUIT-02',
        name: 'สปริงเกอร์ สำหรับลองกอง/ลำไย 3/4"',
        waterVolumeLitersPerHour: [25, 80],
        radiusMeters: [6, 18],
        pressureBar: [1, 4],
        price: 120.0,
    },
    {
        id: 47,
        productCode: 'FRUIT-03',
        name: 'สปริงเกอร์ สำหรับมะม่วง/ขนุน 1.25"',
        waterVolumeLitersPerHour: [50, 150],
        radiusMeters: [10, 28],
        pressureBar: [1.5, 5],
        price: 220.0,
    },

    // === เพิ่มใหม่ - สปริงเกอร์ปรับองศาได้ ===
    {
        id: 48,
        productCode: 'ADJ-01',
        name: 'สปริงเกอร์ ปรับองศา 90°-360° ขนาด 3/4"',
        waterVolumeLitersPerHour: [10, 30],
        radiusMeters: [4, 10],
        pressureBar: [0.8, 3.5],
        price: 75.0,
    },
    {
        id: 49,
        productCode: 'ADJ-02',
        name: 'สปริงเกอร์ ปรับองศา 90°-360° ขนาด 1"',
        waterVolumeLitersPerHour: [18, 50],
        radiusMeters: [6, 15],
        pressureBar: [1, 4],
        price: 95.0,
    },
    {
        id: 50,
        productCode: 'ADJ-03',
        name: 'สปริงเกอร์ ปรับองศา 45°-360° ขนาด 1.25"',
        waterVolumeLitersPerHour: [30, 85],
        radiusMeters: [8, 20],
        pressureBar: [1.2, 4.5],
        price: 135.0,
    },

    // === เพิ่มใหม่ - สปริงเกอร์แรงดันสูงพิเศษ ===
    {
        id: 51,
        productCode: 'HIGHP-01',
        name: 'สปริงเกอร์ แรงดันสูง 3/4" ทนทาน',
        waterVolumeLitersPerHour: [15, 45],
        radiusMeters: [8, 18],
        pressureBar: [3, 10],
        price: 185.0,
    },
    {
        id: 52,
        productCode: 'HIGHP-02',
        name: 'สปริงเกอร์ แรงดันสูง 1" โลหะ',
        waterVolumeLitersPerHour: [25, 75],
        radiusMeters: [10, 25],
        pressureBar: [4, 12],
        price: 320.0,
    },
    {
        id: 53,
        productCode: 'HIGHP-03',
        name: 'สปริงเกอร์ แรงดันสูงพิเศษ 1.5" โลหะหนา',
        waterVolumeLitersPerHour: [60, 180],
        radiusMeters: [15, 40],
        pressureBar: [5, 15],
        price: 650.0,
    }
];